name: PRISM Indexer
run-name: PRISM Indexer ${{ matrix.network }}

on:
  workflow_dispatch:
    inputs:
      network:
        description: "network: mainnet|preview|preprod"
        required: true
        type: choice
        default: 'mainnet'
        options: 
        - mainnet
        - preview
        - preprod
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes for all networks

jobs:
  indexer-job:
    name: Indexer job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: [mainnet, preview, preprod]
    permissions:
      contents: write
    steps:
      - uses: actions/cache@v4
        with:
          path: .
          key: cache-git-${{ matrix.network }}
      - uses: actions/checkout@v4
      - name: Run Indexer inside Docker
        uses: addnab/docker-run-action@v3
        with:
            image: fmgp/prism-indexer:latest
            options: -v ${{ github.workspace }}/${{ matrix.network }}:/data
            run: |
              java -XX:+UseContainerSupport -jar /prism-indexer.jar ./data ${{ matrix.network }} ${{ matrix.network == 'mainnet' && secrets.BLOCKFROST_APIKEY_MAINNET || matrix.network == 'preview' && secrets.BLOCKFROST_APIKEY_PREVIEW || secrets.BLOCKFROST_APIKEY
