name: PRISM Indexer
run-name: PRISM Indexer

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes for all networks

jobs:
  indexer-job:
    name: Indexer job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .
          key: cache-git

      # Subtask for mainnet
      - name: Run Indexer for mainnet
        uses: addnab/docker-run-action@v3
        with:
          image: fmgp/prism-indexer:latest
          options: -v ${{ github.workspace }}/mainnet:/data
          run: |
            java -XX:+UseContainerSupport -jar /prism-indexer.jar ./data mainnet ${{ secrets.BLOCKFROST_APIKEY_MAINNET }}

      # Subtask for preview
      - name: Run Indexer for preview
        uses: addnab/docker-run-action@v3
        with:
          image: fmgp/prism-indexer:latest
          options: -v ${{ github.workspace }}/preview:/data
          run: |
            java -XX:+UseContainerSupport -jar /prism-indexer.jar ./data preview ${{ secrets.BLOCKFROST_APIKEY_PREVIEW }}

      # Subtask for preprod
      - name: Run Indexer for preprod
        uses: addnab/docker-run-action@v3
        with:
          image: fmgp/prism-indexer:latest
          options: -v ${{ github.workspace }}/preprod:/data
          run: |
            java -XX:+UseContainerSupport -jar /prism-indexer.jar ./data preprod ${{ secrets.BLOCKFROST_APIKEY_PREPROD }}

      - name: Cleanup docker-run-action artifacts
        run: |
          rm -f semicolon_delimited_script
          git status

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: Indexer job (all networks)

      - name: Check for changes detected
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: Check for no changes detected
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
