name: PRISM Indexer
run-name: PRISM Indexer

on:
  workflow_dispatch:
    inputs:
      network:
        description: "network: mainnet|preprod"
        required: true
        type: choice
        default: 'mainnet'
        options: 
        - mainnet
        - preprod
  push:
    branches: [master]
    tags: ["v*"]

jobs:
  indexer-job:
    name: Indexer job
    runs-on: ubuntu-latest
    # container:
    #   image: fmgp/prism-indexer:latest
    #   #env:
    #   #volumes:
    #   #options: --cpus 1
    steps:
      - uses: actions/cache@v4
        with:
          path: .
          key: cache-git
      - uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0 # Needed for the release tag // `git fetch --tags` will also work
      - run: |
          pwd
          ls -la
      - name: Run Indexer inside Docker
        uses: addnab/docker-run-action@v3
        with:
            image: aschmelyun/cleaver:latest
            options: -v ${{ github.workspace }}/${{inputs.network}}:/data
            run: |
              pwd
              ls -la
              ls -la data/
              java -XX:+UseContainerSupport -jar /prism-indexer.jar ./data ${{inputs.network}} ${{ secrets.APIKEY }}
      # - name: Indexer
      #   run: java -XX:+UseContainerSupport -jar /prism-indexer.jar ./${{inputs.network}} ${{inputs.network}} ${{ secrets.APIKEY }}
        #docker run --rm -it --entrypoint "sh" --memory="300m" --cpus="1.0" --volume ./mainnet:/data fmgp/prism-indexer -c "java -XX:+UseContainerSupport -jar prism-indexer.jar /data mainnet $APIKEY"
      - run: |
          pwd
          ls -la
